### ISSUE TITLE
WARNING: Detected 6 Thread(s) started in app boot

### ISSUE THREAD

**Issue by blairanderson** [oldmoe/litestack#126]
```text
2024-08-20T21:19:17.784679+00:00 app[web.1]: [2] * Listening on http://0.0.0.0:11331
2024-08-20T21:19:17.784698+00:00 app[web.1]: [2] ! WARNING: Detected 6 Thread(s) started in app boot:
2024-08-20T21:19:17.784721+00:00 app[web.1]: [2] ! #<Thread:0x00007ff4dc325018 /app/vendor/bundle/ruby/3.1.0/gems/litestack-0.4.3/lib/litestack/litejobqueue.rb:182 sleep> - /app/vendor/bundle/ruby/3.1.0/gems/litestack-0.4.3/lib/litestack/litejobqueue.rb:203:in `sleep'
2024-08-20T21:19:17.784736+00:00 app[web.1]: [2] ! #<Thread:0x00007ff4dc324e88 /app/vendor/bundle/ruby/3.1.0/gems/litestack-0.4.3/lib/litestack/litejobqueue.rb:182 sleep> - /app/vendor/bundle/ruby/3.1.0/gems/litestack-0.4.3/lib/litestack/litejobqueue.rb:203:in `sleep'
2024-08-20T21:19:17.784747+00:00 app[web.1]: [2] ! #<Thread:0x00007ff4dc324d98 /app/vendor/bundle/ruby/3.1.0/gems/litestack-0.4.3/lib/litestack/litejobqueue.rb:182 sleep> - /app/vendor/bundle/ruby/3.1.0/gems/litestack-0.4.3/lib/litestack/litejobqueue.rb:203:in `sleep'
2024-08-20T21:19:17.784752+00:00 app[web.1]: [2] ! #<Thread:0x00007ff4dc324ca8 /app/vendor/bundle/ruby/3.1.0/gems/litestack-0.4.3/lib/litestack/litejobqueue.rb:182 sleep> - /app/vendor/bundle/ruby/3.1.0/gems/litestack-0.4.3/lib/litestack/litejobqueue.rb:203:in `sleep'
2024-08-20T21:19:17.784764+00:00 app[web.1]: [2] ! #<Thread:0x00007ff4dc324b40 /app/vendor/bundle/ruby/3.1.0/gems/litestack-0.4.3/lib/litestack/litejobqueue.rb:182 sleep> - /app/vendor/bundle/ruby/3.1.0/gems/litestack-0.4.3/lib/litestack/litejobqueue.rb:203:in `sleep'
2024-08-20T21:19:17.784775+00:00 app[web.1]: [2] ! #<Thread:0x00007ff4dc324988 /app/vendor/bundle/ruby/3.1.0/gems/litestack-0.4.3/lib/litestack/litejobqueue.rb:214 sleep> - /app/vendor/bundle/ruby/3.1.0/gems/litestack-0.4.3/lib/litestack/litejobqueue.rb:223:in `sleep'
```

I am trying to use the database portion of litestack inside my heroku application. We haven't touched any config for the job queue but we're getting the error that multiple threads are being started for the job queue.

**Comment by blairanderson** [comment]
I ended up changing gemfile: 

`gem "litestack", require: false`

then requiring files manually
```ruby
require "litestack/version"
require "litestack/litesupport"
require "litestack/litedb"
require "active_record/connection_adapters/litedb_adapter" if defined? ActiveRecord
require "railties/rails/commands/dbconsole" if defined?(Rails) && defined?(ActiveRecord)
require "active_support/cache/litecache" if defined? ActiveSupport
require "litestack/railtie" if defined? Rails::Railtie
```

**Comment by blairanderson** [comment]
there are a few paths: 
- new application where user wants all features (opt-out
- new application where user wants some features (opt-in) 
- old application  where user wants some features (opt-in)
