### ISSUE TITLE
Rake tasks not supported by 'litedb' adapter

### ISSUE THREAD

**Issue by netmute** [oldmoe/litestack#2]
Trying to migrate an existing Rails app over to litestack. I'm getting this error when trying to run the `db:test:prepare` task.
The offending sub-task seems to be `db:test:purge`. Log is attached.

```
$ rake db:test:load --trace
** Invoke db:test:load (first_time)
** Invoke db:test:purge (first_time)
** Invoke db:load_config (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute db:load_config
** Invoke db:check_protected_environments (first_time)
** Invoke db:load_config 
** Execute db:check_protected_environments
** Execute db:test:purge
rake aborted!
ActiveRecord::Tasks::DatabaseNotSupported: Rake tasks not supported by 'litedb' adapter
/Users/se/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/activerecord-7.0.4.2/lib/active_record/tasks/database_tasks.rb:544:in `class_for_adapter'
/Users/se/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/activerecord-7.0.4.2/lib/active_record/tasks/database_tasks.rb:534:in `database_adapter_for'
/Users/se/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/activerecord-7.0.4.2/lib/active_record/tasks/database_tasks.rb:341:in `purge'
/Users/se/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/activerecord-7.0.4.2/lib/active_record/railties/databases.rake:568:in `block (4 levels) in <main>'
/Users/se/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/activerecord-7.0.4.2/lib/active_record/railties/databases.rake:567:in `each'
/Users/se/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/activerecord-7.0.4.2/lib/active_record/railties/databases.rake:567:in `block (3 levels) in <main>'
/Users/se/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
/Users/se/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
/Users/se/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
/Users/se/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/Users/se/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/Users/se/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/Users/se/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:243:in `block in invoke_prerequisites'
/Users/se/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:241:in `each'
/Users/se/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:241:in `invoke_prerequisites'
/Users/se/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
/Users/se/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/Users/se/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/Users/se/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
/Users/se/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
/Users/se/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/Users/se/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
/Users/se/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
/Users/se/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
/Users/se/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
/Users/se/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:83:in `block in run'
/Users/se/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/se/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:80:in `run'
/Users/se/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/Users/se/.rbenv/versions/3.2.0/bin/rake:25:in `load'
/Users/se/.rbenv/versions/3.2.0/bin/rake:25:in `<main>'
Tasks: TOP => db:test:load => db:test:purge
```

**Comment by netmute** [comment]
I found the issue. There are a lot of references to `ultralite` in the code, probably a leftover from an old version of the project?

In particular `lib/active_record/connection_adapters/litedb_adapter.rb` has these lines:
```rb
    module DatabaseTasks
      register_task(/ultralite/, "ActiveRecord::Tasks::LitedbDatabaseTasks")
    end
```

Changing `ultralite` to `litedb` fixes this issue.

**Comment by oldmoe** [comment]
Thanks @netmute for finding this out, indeed this is a left over from an older version, I will prepare a fix right away
